name: Node.js CI/CD
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.changeset/**'
      - 'apps/**'
      - 'packages/**'
      - '!examples/**'
      - '!.github/**'
      - '!.husky/**'
      - '!.vscode/**'
      - '!**/README.md'
      - '!**/CHANGELOG.md'
      - '!**/LICENSE'
      - '!packages/**/__tests__/**'
  pull_request:
    branches:
      - main
    paths:
      - '.changeset/**'
      - 'apps/**'
      - 'packages/**'
      - '!examples/**'
      - '!.github/**'
      - '!.husky/**'
      - '!.vscode/**'
      - '!**/README.md'
      - '!**/CHANGELOG.md'
      - '!**/LICENSE'
      - '!packages/**/__tests__/**'
env:
  TZ: "Europe/Amsterdam"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PNPM
        uses: pnpm/action-setup@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: 'pnpm'

      - name: Setup Turbo cache
        uses: actions/cache@v3
        with:
          path: node_modules/.cache/turbo
          key: turbo-${{ github.job }}-${{ github.ref_name }}-${{ github.sha }}
          restore-keys: turbo-${{ github.job }}-${{ github.ref_name }}-

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm run lint

      - name: Build
        run: |
          pnpm run build

      - name: Test
        run: pnpm run test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd ~/my-medusa-store
            git pull
            git status
            pnpm prune
            pnpm install
            pnpm run build
            pm2 restart medusa-backend
            pm2 restart medusa-storefront
            pm2 reload all
